#!/usr/bin/env bash

set -euo pipefail

if [[ -f src/polyfill.js ]]; then

  printf "Building src/polyfill.js\n"

  mkdir -p dst/

  npx swc src/polyfill.js -o dst/polyfill.optimized.js

  if [[ "${MODE:-development}" == production ]]; then

    npx rolldown dst/polyfill.optimized.js -o dst/polyfill.js -f iife -m

  else

    npx rolldown dst/polyfill.optimized.js -o dst/polyfill.js -f iife

  fi

  rm dst/polyfill.optimized.js

fi

printf "Done\n"

